"""int to bigint

Revision ID: 16de891f22f3
Revises: bf64362c324c
Create Date: 2025-05-25 15:14:07.565642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16de891f22f3"
down_revision: Union[str, None] = "bf64362c324c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegram_chats",
        "chat_token",
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegram_chats",
        "chat_token",
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
